// Recipe — Simple C++ Profiler
// Compiles main.cpp (sorting benchmark), runs it, parses the timing table,
// then opens Apple Notes and pastes a formatted profiling report.
//
// Run: simulang run main.ts

import { execSync } from 'node:child_process'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  App, FocusPolicy, Visibility,
  KeyboardController, Key, Direction,
  Clipboard,
  initLogger,
} from '@simular-ai/simulang-js'

initLogger(null, 'warn')

const sleep = (ms: number) => new Promise<void>((r) => setTimeout(r, ms))
const kb = new KeyboardController()

const __dirname = dirname(fileURLToPath(import.meta.url))
const CPP  = join(__dirname, 'main.cpp')
const BIN  = join(__dirname, 'profiler_bin')

// ─── Compile ──────────────────────────────────────────────────────────────────

console.log('⚙️  Compiling main.cpp…')
try {
  execSync(`clang++ -O2 -std=c++17 -o "${BIN}" "${CPP}"`, { encoding: 'utf8' })
  console.log('    Compiled OK\n')
} catch (e: unknown) {
  const msg = e instanceof Error ? e.message : String(e)
  console.error('Compilation failed:\n' + msg)
  process.exit(1)
}

// ─── Run ──────────────────────────────────────────────────────────────────────

console.log('🏃  Running benchmark…')
let rawOutput: string
try {
  rawOutput = execSync(`"${BIN}"`, { encoding: 'utf8' })
} catch (e: unknown) {
  const msg = e instanceof Error ? e.message : String(e)
  console.error('Run failed:\n' + msg)
  process.exit(1)
}

console.log(rawOutput)

// ─── Parse results ────────────────────────────────────────────────────────────

interface Row { size: number; bubble: number; merge: number; std: number }
const rows: Row[] = []

for (const line of rawOutput.split('\n')) {
  const parts = line.trim().split(/\s+/)
  if (parts.length < 4 || isNaN(Number(parts[0]))) continue
  rows.push({
    size:   parseInt(parts[0]),
    bubble: parseFloat(parts[1]),
    merge:  parseFloat(parts[2]),
    std:    parseFloat(parts[3]),
  })
}

// ─── Format report ────────────────────────────────────────────────────────────

const now = new Date().toLocaleString('en-SG')
let report = `C++ Sorting Benchmark — ${now}\n`
report += `Compiler: clang++ -O2 -std=c++17  |  macOS  |  Averaged over 3 runs\n`
report += `${'─'.repeat(60)}\n\n`

report += `Results (milliseconds):\n\n`
report += `${'Size'.padEnd(10)}${'BubbleSort'.padEnd(18)}${'MergeSort'.padEnd(18)}${'std::sort'.padEnd(18)}\n`
report += `${'─'.repeat(64)}\n`
for (const r of rows) {
  const bubble = r.bubble.toFixed(3)
  report += `${String(r.size).padEnd(10)}${bubble.padEnd(18)}${r.merge.toFixed(3).padEnd(18)}${r.std.toFixed(3).padEnd(18)}\n`
}

report += `\nKey observations:\n`
if (rows.length >= 2) {
  const small = rows[0], large = rows[rows.length - 1]
  const mergeRatio = (large.merge / small.merge).toFixed(1)
  const stdRatio   = (large.std   / small.std).toFixed(1)
  const sizeRatio  = large.size / small.size
  report += `• Array size grew ${sizeRatio}× (${small.size} → ${large.size})\n`
  report += `• MergeSort time grew ${mergeRatio}× — consistent with O(n log n)\n`
  report += `• std::sort time grew ${stdRatio}× — also O(n log n), tighter constants\n`
  if (small.bubble !== null && rows[2]?.bubble !== null) {
    const bubbleRow = rows.find(r => r.bubble !== null && r.size >= 10000)
    if (bubbleRow?.bubble) {
      const bubbleRatio = (bubbleRow.bubble / (small.bubble ?? 1)).toFixed(0)
      report += `• BubbleSort grew ~${bubbleRatio}× for a ${bubbleRow.size / small.size}× size increase — demonstrating O(n²) scaling\n`
    }
  }
  report += `• std::sort consistently outperforms hand-rolled MergeSort (cache-friendly introsort)\n`
}

report += `\nGenerated by simulang simple-profiler`

console.log('📋  Report:\n')
console.log(report)

// ─── Open Notes and paste ─────────────────────────────────────────────────────

console.log('\n📝  Opening Apple Notes…')
const notes = App.exactName('Notes').open(null, FocusPolicy.Steal, Visibility.Show, true)
await sleep(1500)
notes.focus()
await sleep(500)

// Cmd+N → new note
kb.key(Key.Meta, Direction.Press)
kb.key(Key.N, Direction.Click)
kb.key(Key.Meta, Direction.Release)
await sleep(800)

// Ensure focus is inside the note body before pasting
notes.focus()
await sleep(300)

new Clipboard().pasteText(report)
console.log('✅  Report pasted into Notes.')
